from __future__ import annotations

import qudits_on_qubits
from qudits_on_qubits.experiments import WorkloadOptimizationConfig


def test_top_level_workload_optimization_config_alias_matches_experiments_export():
    assert qudits_on_qubits.WorkloadOptimizationConfig is WorkloadOptimizationConfig
